{% set name = "jproperties" %}
{% set version = "2.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jproperties-{{ version }}.tar.gz
  sha256: 036fcd52c10a8a1c21e6fa2a1c292c93892e759b76490acc4809213a36ddc329

build:
  number: 0
  noarch: python
  entry_points:
    - propconv = jproperties:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools_scm ~= 3.3
    - python 2.7|>=3.6
  run:
    - python 2.7|>=3.6
    - six ~=1.13

test:
  imports:
    - jproperties
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Tblue/python-jproperties
  summary: Java Property file parser and writer for Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melonhead901
